baseurl = "http://example.org"
title = "MIT Class of 2017 Alumni Council"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Dimension"
  description = 'We are the MIT Class of 2017 Alumni Council. Please use this webpage to <i>keep in touch with your classmates</i> 
  <br>Get Involved <a href="https://docs.google.com/forms/d/e/1FAIpQLSdvwK_1YI1wudoePuuoxnJjIJiY7uNM6L4rjrQYk6JZQKJhZA/viewform?usp=sf_link">(Link)</a>'
  logo = "fa-graduation-cap"
  copyright = "MIT 2017 Alumni Council"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "MIT Class of 2017 Alumni Council"
